name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
        
    - name: Run tests
      run: |
        pytest tests/ --cov=src/ --cov-report=xml
        
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml

  build:
    needs: test
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Create icon
      run: python src/utils/create_icon.py
      
    - name: Build executable
      run: python src/build_exe.py
      
    - name: Create portable version
      run: |
        mkdir release\portable
        xcopy /E /I /Y dist\AI文章生成助手 release\portable
        copy README.md release\portable\
        copy requirements.txt release\portable\
        
    - name: Create ZIP archive
      run: |
        cd release\portable
        7z a -tzip ..\AI文章生成助手_便携版_${{ github.ref_name }}.zip *
        
    - name: Build installer
      run: |
        choco install innosetup
        iscc installer.iss
        
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/AI文章生成助手_便携版_${{ github.ref_name }}.zip
          release/installer/AI文章生成助手_安装程序_${{ github.ref_name }}.exe
        draft: false
        prerelease: false
        body: |
          AI文章生成助手 ${{ github.ref_name }} 发布
          
          ### 更新内容
          - 请在此处添加版本更新说明
          
          ### 下载
          - 便携版：AI文章生成助手_便携版_${{ github.ref_name }}.zip
          - 安装版：AI文章生成助手_安装程序_${{ github.ref_name }}.exe 